# Generated by Django 5.2.8 on 2025-11-13 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
