# Generated by Django 5.2.8 on 2025-11-13 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_prescription_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='doctor',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name='doctor',
            name='date_of_birth',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='doctor',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='doctor_photos/'),
        ),
        migrations.AddField(
            model_name='doctor',
            name='working_hours',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='blood_type',
            field=models.CharField(blank=True, max_length=5),
        ),
        migrations.AddField(
            model_name='patient',
            name='contact_number',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
