# Generated by Django 5.2.8 on 2025-11-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_patientnote'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='humidity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='room_temperature',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
