# Generated by Django 5.2.8 on 2025-11-22 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_patient_address_patient_medical_condition_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='profile_photo',
            field=models.ImageField(blank=True, null=True, upload_to='patient_photos/'),
        ),
    ]
