# Generated by Django 5.2.8 on 2025-11-22 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_patient_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='sensorreading',
            name='battery_level',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='sensorreading',
            name='signal_strength',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
