# Generated by Django 5.2.8 on 2025-11-22 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_sensorreading_battery_level_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='doctor',
            name='telegram_chat_id',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
